spring.application.name=demo

## Database Properties
spring.datasource.url=jdbc:mysql://localhost:3306/structure?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=CoNhanThi27

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
#JWT
app.jwt.secret=PLEASE_CHANGE_THIS_SECRET_KEY_32CHARS_MINIMUM
app.jwt.expiration-seconds=3600
app.jwt.issuer=demo-api

debug=true
